version: "3.4"
services:
  consul:
    image: consul:1.2.3
    hostname: consul
    volumes:
    - /opt/consul_data:/consul/data
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0 -bind=127.0.0.1
    network_mode: host
#    networks:
#    - vaultexample
    ports:
    - 8400:8400
    - 8500:8500
    - 8600:53/udp

  vault:
    depends_on:
    - consul
    image: vault:0.11.3
    hostname: vault
    ports:
    - 8200:8200
    network_mode: host
#    networks:
#    - vaultexample
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    volumes:
    - ./wait-for:/wait-for
    - ./config:/config/
    entrypoint: /wait-for 127.0.0.1:8500 -t 30 -- vault server -config=/config/consul.hcl

#networks:
#  vaultexample:

